### ISSUE TITLE
progressbar wisible after page is loaded

### ISSUE THREAD

**Issue by baxandrei** [flagrow/user-directory#11]
The progress bar (loading spinner circle) is show before to load member list, and still visible after member list is shown.

Before load complete: https://i62.servimg.com/u/f62/17/31/96/85/screen20.png
After load complete: https://i62.servimg.com/u/f62/17/31/96/85/screen21.png
(spinner is visible in "after load complete" photo, on the green background on member Ralkage).

**Comment by luceos** [comment]
Thanks for reporting, still need to take a look at that.

https://github.com/flagrow/user-directory/issues/8
