### ISSUE TITLE
Compatibility with Beta 8

### ISSUE THREAD

**Issue by PeopleInside** [flagrow/user-directory#20]
Waiting to see compatibility with Beta 8 for manage registered users.

**Comment by luceos** [comment]
working on it ;)

https://forum.flagrow.io/d/9-state-of-flagrow-extensions-for-beta-8

**Comment by PeopleInside** [comment]
user-list ? is another plugin?

**Comment by luceos** [comment]
Yes this one wasn't listed yet, thanks.

**Comment by PeopleInside** [comment]
Umh there is a github page where i can activate notification for new release? I am subscrived to this plugin user-directoy, if this will be updated to Beta 8 ok, if not i need find the plugin that will be compatible with Beta 8. The most important things is be able to have a list of users. Thanks again :)

**Comment by luceos** [comment]
Yes feel free to subscribe to releases. Or follow https://twitter.com/flagrowio ;)

**Comment by PeopleInside** [comment]
Yes but with link? Where is the plugin link? Is this one on GitHub or is another?

**Comment by luceos** [comment]
![image](https://user-images.githubusercontent.com/504687/49438228-084e5b80-f7be-11e8-88c8-016b8e3d2308.png)

This is the one for the public user list, the users-list extensions is for the one that shows the list in the admin and allows for mass mailing (or something like it).
