### ISSUE TITLE
/users 500 on beta.8

### ISSUE THREAD

**Issue by tooreht** [flagrow/user-directory#23]
I encountered this error on master (`b8147de17d`) using flarum beta.8:

![screenshot-localhost-8888-2019 02 26-14-24-14](https://user-images.githubusercontent.com/2290727/53415963-c73ba100-39d2-11e9-8bf9-fdb6a9ed6a25.png)

If somebody can give me some hints on how to fix this, I will try to contribute.

**Comment by luceos** [comment]
It's not compatible with beta 8. In order to make it compatible all changes have to be applied related to the backend changes in flarum/core.

**Comment by clarkwinkelmann** [comment]
Fixed on master

**Comment by tooreht** [comment]
Thank you for your efforts @clarkwinkelmann! Looking forward to test it next week 🙂
