### ISSUE TITLE
Allow linking the directory, make it optional though

### ISSUE THREAD

**Issue by luceos** [flagrow/user-directory#3]
We should provide an access point for the user directory. We could allow something like that in the header or in the sidebar.

**Comment by AngellitoX** [comment]
I'd like to suggest and request for the access point to be where the tags are, to avoid overloading the header menu. The picture reference is here:

https://i.imgur.com/8ICVQyH.jpg

Thank you Luceos!

**Comment by Luceos** [comment]
![image](https://cloud.githubusercontent.com/assets/504687/26048440/6ff51db8-3957-11e7-9433-1671dca353dc.png)
