### ISSUE TITLE
Issues found on Mobile version

### ISSUE THREAD

**Issue by AngellitoX** [flagrow/user-directory#6]
The right-side button on the top of the page, leads to the navbar as if you were editing a profile and when you finally click to 'Edit' it leads you to a random account.

https://i.imgur.com/7UCWevI.png

Also, the middle button I think it should say something like "Users/Members" as in every other section. If I am wrong, please forgive me.

https://i.imgur.com/2O76ri4.png

**Comment by Luceos** [comment]
@AngellitoX you are aware you can simply paste the image here right ;) Much easier :D

**Comment by AngellitoX** [comment]
Yes @Luceos, sorry about that. I was in my mobile last night and it didnt let me to past them :(

**Comment by Luceos** [comment]
What's the reason for closing this?

**Comment by AngellitoX** [comment]
What? I don't remember closing this at all!

**Comment by clarkwinkelmann** [comment]
I can't reproduce on the latest version. Feel free to reopen if you still experience this.

Please include the platform, browser and browser version and whether you can replicate on other browsers.
