### ISSUE TITLE
Allow filtering by user groups

### ISSUE THREAD

**Issue by uamv** [flagrow/user-directory#7]
It would be great to have the option to filter all users according to groups as set via Flarum core. I don't know whether this would best happen via the already available dropdown or via a secondary filter (a dedicated dropdown for groups).

**Comment by Luceos** [comment]
Hi @uamv also love the idea, hence #4 ;) It's blocked though due to the inability to modify the permission group edit modal.

**Comment by uamv** [comment]
Ha. how'd I miss that? Good to hear you're on it!

**Comment by Luceos** [comment]
No problem, great minds think alike 😁
